name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: validate YML file
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./**/action.yml
          config_data: "{extends: default, rules: {line-length: disable}}"
