name: User-Usage

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    name: example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      ## Download github-actions-toolbox first
      - name: Checkout github-actions-toolbox
        uses: actions/checkout@v3
        with:
          repository: VelocityLight/github-actions-toolbox
          ref: main
          path: github-actions-toolbox

      - name: Show file
        run: |
          ls -la
          cd github-actions-toolbox
          ls -la

      ## Use tool that you need
      - name: Use tool
        uses: ./github-actions-toolbox/test-user-usage
        with:
          name: ${{ github.event.pull_request.user.login }}
